// Next core component here
import Head from 'next/head';
import Image from 'next/image';

// Components here
import Banner from '../components/banner-component/banner'
import Card from '../components/card-component/card';

// Static files here
import styles from '../styles/Home.module.css';

export async function getStaticProps(context) {
  const response = await fetch("https://api.neshan.org/v1/search?term=%DA%A9%D8%A7%D9%81%DB%8C%D8%B4%D8%A7%D9%BE&lat=38.061691&lng=46.266077", {
    "method": "GET",
    "headers": {
      "user-agent": "vscode-restclient",
      "api-key": "service.Dg6NkD6DNwr4N5zAnxlH0AMsum5yVsU8LYUwLV7e"
    }
  })
  const jsonData = await response.json();
  const coffeeStores = jsonData.items;
  return {
    props: {
      coffeeStores,
    },
  }
}

export default function Home({ coffeeStores }) {
  const handleOnBannerBtnCLick = () => {
    console.log("Hey button clicked!");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>کافه جو</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Banner 
            buttonText="نمایش مغازه های اطراف"
            handleOnClick={handleOnBannerBtnCLick}
          />
          <div className={styles.imageContainer}>
            <Image src="/static/img/coffee-man.png" width={300} height={471} />
          </div>
        </div>
        {coffeeStores.length > 0 && 
          <>
            <h2 className={styles.coffeeShopListTitle}>کافی شاپ های تهران</h2>
            <div className={styles.wholeCardsContainer}>
              {coffeeStores.map(store => {
                return <Card {...store} key={store.id}/>
              })}
            </div>
          </>  
        }
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
