// Next core component here
import Head from 'next/head';
import Image from 'next/image';

// Components here
import Banner from '../components/banner-component/banner'
import Card from '../components/card-component/card';

// Static files here
import styles from '../styles/Home.module.css';

export async function getStaticProps(context) {
  const response = await fetch("https://map.ir/search/v2", {
    "method": "GET",
    "headers": {
      "user-agent": "vscode-restclient",
      "content-type": "application/json",
      "x-api-key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQzOGQ5MWYxNzgwZWY3MmU2ODFlZjgyN2QzYjY2OWQxMTgxZGI5ZWZjMzlhYzU0M2IyOTMxYzEzMDEwMGUzZmI1MThiZWQ0YTdmYjQzM2Q0In0.eyJhdWQiOiIxODA2MCIsImp0aSI6ImQzOGQ5MWYxNzgwZWY3MmU2ODFlZjgyN2QzYjY2OWQxMTgxZGI5ZWZjMzlhYzU0M2IyOTMxYzEzMDEwMGUzZmI1MThiZWQ0YTdmYjQzM2Q0IiwiaWF0IjoxNjUzMzg2Nzk4LCJuYmYiOjE2NTMzODY3OTgsImV4cCI6MTY1NTk3ODc5OCwic3ViIjoiIiwic2NvcGVzIjpbImJhc2ljIl19.CRa6je-XMxXUrXqKYCrMV8mNrbgjVMnBOQ2R0znbRFEMPtCjNpFyVrVORQT9P6H97Y-PITk3w7rkjd03zLXcW4U5KY7Km4sDIwhCbIOSkhdjUtXGA7Pckk88YtYfECKIPL2VSZxeVIWhxR5ju7lhpzHlXJPNYBxEokt-TnWTzTqZaI90CD7UbT1RtHy4DjLv03idq8811BgdKwnrUIMmMe_ZfqdgIcMqpehSHUCpcu9km357z_did1q3BmZrJcBtr4Hb3UbfGl9j43PWZ_ETwakfJ7W1U_nD4euLE078T0KVuFqLJnlTZPD6GZ43K3yfyUTaRyRLion0Te9nUYYDfA"
    },
    "body": {
      "text": "کافی شاپ",
      "": "city eq تبریز",
      "lat": 38.061691,
      "lon": 46.266077
    }
  })
  const jsonData = await response.json();
  const coffeeStores = jsonData.items;
  return {
    props: {
      coffeeStores,
    },
  }
}

export default function Home({ coffeeStores }) {
  const handleOnBannerBtnCLick = () => {
    console.log("Hey button clicked!");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>کافه جو</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Banner 
            buttonText="نمایش مغازه های اطراف"
            handleOnClick={handleOnBannerBtnCLick}
          />
          <div className={styles.imageContainer}>
            <Image src="/static/img/coffee-man.png" width={300} height={471} />
          </div>
        </div>
        {coffeeStores.length > 0 && 
          <>
            <h2 className={styles.coffeeShopListTitle}>کافی شاپ های تهران</h2>
            <div className={styles.wholeCardsContainer}>
              {coffeeStores.map(store => {
                return <Card {...store} key={store.id}/>
              })}
            </div>
          </>  
        }
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
