// Next core component here
import Head from 'next/head';
import Image from 'next/image';

// Components here
import Banner from '../components/banner-component/banner'
import Card from '../components/card-component/card';

// Static files here
import styles from '../styles/Home.module.css';

// Data files here
import data from '../data/coffee-store.json';

export async function getStaticProps(context) {
  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }) {
  const handleOnBannerBtnCLick = () => {
    console.log("Hey button clicked!");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>کافه جو</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Banner 
            buttonText="نمایش مغازه های اطراف"
            handleOnClick={handleOnBannerBtnCLick}
          />
          <div className={styles.imageContainer}>
            <Image src="/static/img/coffee-man.png" width={300} height={471} />
          </div>
        </div>
        {data.length > 0 && 
          <>
            <h2 className={styles.coffeeShopListTitle}>کافی شاپ های تهران</h2>
            <div className={styles.wholeCardsContainer}>
              {data.map(store => {
                return <Card {...store} key={store.id}/>
              })}
            </div>
          </>  
        }
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
