GET https://map.ir/search/v2
Content-Type: application/json
x-api-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQzOGQ5MWYxNzgwZWY3MmU2ODFlZjgyN2QzYjY2OWQxMTgxZGI5ZWZjMzlhYzU0M2IyOTMxYzEzMDEwMGUzZmI1MThiZWQ0YTdmYjQzM2Q0In0.eyJhdWQiOiIxODA2MCIsImp0aSI6ImQzOGQ5MWYxNzgwZWY3MmU2ODFlZjgyN2QzYjY2OWQxMTgxZGI5ZWZjMzlhYzU0M2IyOTMxYzEzMDEwMGUzZmI1MThiZWQ0YTdmYjQzM2Q0IiwiaWF0IjoxNjUzMzg2Nzk4LCJuYmYiOjE2NTMzODY3OTgsImV4cCI6MTY1NTk3ODc5OCwic3ViIjoiIiwic2NvcGVzIjpbImJhc2ljIl19.CRa6je-XMxXUrXqKYCrMV8mNrbgjVMnBOQ2R0znbRFEMPtCjNpFyVrVORQT9P6H97Y-PITk3w7rkjd03zLXcW4U5KY7Km4sDIwhCbIOSkhdjUtXGA7Pckk88YtYfECKIPL2VSZxeVIWhxR5ju7lhpzHlXJPNYBxEokt-TnWTzTqZaI90CD7UbT1RtHy4DjLv03idq8811BgdKwnrUIMmMe_ZfqdgIcMqpehSHUCpcu9km357z_did1q3BmZrJcBtr4Hb3UbfGl9j43PWZ_ETwakfJ7W1U_nD4euLE078T0KVuFqLJnlTZPD6GZ43K3yfyUTaRyRLion0Te9nUYYDfA

{
    "text": "کافی شاپ",
    "$filter": "city eq تبریز",
    "lat": 38.061691,
    "lon": 46.266077
}